Repository EasyScriptJS/EasyScript, pull requests merged in 2023-01, with the labels that each got.

#1 v1.0.0
  README.md
  package-lock.json
  package.json
  src/functions/log.js
  src/functions/print.js
  src/index.js
  src/modules.js
Labels: release

#3 v1.0.1
  README.md
  package-lock.json
  package.json
  src/modules.js
  src/modules/flip.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
Labels: release

#4 v1.0.2
  README.md
  package-lock.json
  package.json
Labels: release

#6 v1.0.3
  README.md
Labels: release, bug fix

#8 v1.0.4
  README.md
Labels: release

#18 v1.0.5
  README.md
  package-lock.json
  package.json
Labels: release, fix

#17 v1.1.0
  README.md
  package-lock.json
  package.json
  src/modules.js
  src/modules/util.js
  src/modules/util/boolToNum.js
  src/modules/util/boolToStr.js
  src/modules/util/numToStr.js
  src/modules/util/strToBool.js
  src/modules/util/strToNum.js
  src/modules/uuid.js
Labels: release

#20 v1.1.1
  package-lock.json
  package.json
  src/modules/random.js
Labels: release, fix

#22 v1.1.2
  package-lock.json
  package.json
  src/modules.js
  src/modules/util.js
Labels: release, fix

#23 v1.1.3
  package-lock.json
  package.json
  src/modules.js
Labels: release, fix

#25 added remove duplicates module
  src/modules.js
  src/modules/removeDuplicates.js
Labels: enhancement, next release

#27 feat(issues): add templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
Labels: enhancement

#26 feat: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#24 v1.1.4
  README.md
  package-lock.json
  package.json
  src/modules.js
  src/modules/flip.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/types/boolToNum.js
  src/modules/types/boolToStr.js
  src/modules/types/numToBool.js
  src/modules/types/numToStr.js
  src/modules/types/strToBool.js
  src/modules/types/strToNum.js
  src/modules/util/numToStr.js
  src/modules/util/removeDuplicates.js
  src/modules/uuid.js
Labels: release, wip, fix

#30 self documentation, fixed typo
  package-lock.json
  src/modules.js
  src/modules/flip.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/util/removeDuplicates.js
  src/modules/uuid.js
Labels: fix, enhancement, next release

#31 v1.1.5
  package-lock.json
  src/modules.js
  src/modules/flip.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/util/removeDuplicates.js
  src/modules/uuid.js
Labels: release, fix

#33 v1.1.6
  package-lock.json
  package.json
  src/modules.js
Labels: release, fix

#34 Convert to TypeScript
  package.json
  src/index.js
  src/index.ts
  src/modules.js
  src/modules.ts
  src/modules/flip.ts
  src/modules/id.ts
  src/modules/log.ts
  src/modules/print.ts
  src/modules/random.js
  src/modules/random.ts
  src/modules/types/boolToNum.js
  src/modules/types/boolToNum.ts
  src/modules/types/boolToStr.js
  src/modules/types/boolToStr.ts
  src/modules/types/numToBool.js
  src/modules/types/numToBool.ts
  src/modules/types/numToStr.js
  src/modules/types/numToStr.ts
  src/modules/types/strToBool.js
  src/modules/types/strToBool.ts
  src/modules/types/strToNum.js
  src/modules/types/strToNum.ts
  src/modules/util/removeDuplicates.ts
  src/modules/uuid.ts
Labels: enhancement, next release

#42 feat(workflows): labeler + do-not-merge
  .github/labeler.yml
  .github/workflows/do-not-merge.yml
  .github/workflows/labeler.yml
Labels: enhancement

#41 v1.1.7
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  package-lock.json
  package.json
  src/index.js
  src/modules.js
  src/modules/flip.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/types/boolToNum.js
  src/modules/types/boolToStr.js
  src/modules/types/numToBool.js
  src/modules/types/numToStr.js
  src/modules/types/strToBool.js
  src/modules/types/strToNum.js
  src/modules/util/removeDuplicates.js
  src/modules/uuid.js
Labels: release, readme, modules

#43 v1.2.0
  package-lock.json
  package.json
  src/modules.js
  src/modules/flip.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/types/boolToStr.js
  src/modules/types/numToStr.js
  src/modules/types/strToBool.js
  src/modules/util/boolToNum.js
  src/modules/util/boolToStr.js
  src/modules/util/numToBool.js
  src/modules/util/numToStr.js
  src/modules/util/removeDuplicates.js
  src/modules/util/strToBool.js
  src/modules/util/strToNum.js
  src/modules/uuid.js
Labels: release, modules

#45 Move to TypeScript
  .circleci/config.yml
  .github/workflows/publish.yml
  .gitignore
  .npmignore
  .prettierrc.json
  index.ts
  package-lock.json
  package.json
  src/flip.ts
  src/index.js
  src/log.ts
  src/modules.js
  src/modules/flip.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/util/boolToNum.js
  src/modules/util/boolToStr.js
  src/modules/util/numToBool.js
  src/modules/util/numToStr.js
  src/modules/util/removeDuplicates.js
  src/modules/util/strToBool.js
  src/modules/util/strToNum.js
  src/modules/uuid.js
  src/print.ts
  src/random.ts
  src/types/boolToNum.ts
  src/types/boolToStr.ts
  src/types/numToBool.ts
  src/types/numToStr.ts
  src/types/strToBool.ts
  src/types/strToNum.ts
  src/util/removeDuplicates.ts
  src/uuid.ts
  tsconfig.json
Labels: modules

#47 v1.2.1
  .github/labeler.yml
  README.md
  package-lock.json
  package.json
  src/index.js
  src/modules.js
  src/modules/util/removeDuplicates.js
Labels: release, wip, readme, modules

#48 v1.2.2
  package-lock.json
  package.json
  src/index.js
  src/modules/id.js
  src/modules/log.js
  src/modules/print.js
  src/modules/random.js
  src/modules/util/boolToNum.js
  src/modules/util/boolToStr.js
  src/modules/util/numToBool.js
  src/modules/util/numToStr.js
  src/modules/util/strToBool.js
  src/modules/util/strToNum.js
  src/modules/uuid.js
Labels: release, fix, modules

#52 v1.2.3
  README.md
  src/index.js
  src/modules/dns/a.js
  src/modules/dns/cname.js
  src/modules/id.js
  src/modules/uuid.js
Labels: release, readme, modules

#53 fix: package version
  package-lock.json
  package.json
Labels: fix, readme, modules
